name: widgets
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/wolverine.png
    - assets/images/wolverine_2.png
    - assets/images/wolverine_3.png
    - assets/images/wolverine_4.png
    - assets/emojis/angry.svg
    - assets/emojis/heart.svg
    - assets/emojis/laughing.svg
    - assets/emojis/like.svg
    - assets/emojis/sad.svg
    - assets/emojis/shocked.svg
    - assets/wallpapers/1.jpeg
    - assets/wallpapers/2.jpeg
    - assets/wallpapers/3.jpeg
    - assets/wallpapers/4.jpeg
    - assets/wallpapers/5.jpeg
    - assets/wallpapers/6.jpeg
    - assets/users/1.jpg
    - assets/users/2.jpg
    - assets/users/3.jpg
    - assets/users/4.jpg
    - assets/users/5.jpg
    - assets/users/6.jpg
    - assets/users/7.jpg
    - assets/users/8.jpg
    - assets/publications/ferrari.jpeg
    - assets/publications/flutter.jpeg
    - assets/logos/facebook-logo.svg

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

    - family: Nunito
      fonts:
       - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
         weight: 200
         style: italic
       - asset: assets/fonts/nunito/Nunito-Light.ttf
         weight: 300
       - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/nunito/Nunito-Regular.ttf
         weight: 400
       - asset: assets/fonts/nunito/Nunito-Italic.ttf
         weight: 400
         style: italic
       - asset: assets/fonts/nunito/Nunito-Medium.ttf
         weight: 500
       - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/nunito/Nunito-Bold.ttf
         weight: 700
       - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
         weight: 800
         style: italic
       - asset: assets/fonts/nunito/Nunito-Black.ttf
         weight: 900
       - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
         weight: 900
         style: italic
    - family: Titillium
      fonts:
       - asset: assets/fonts/titillium/TitilliumWeb-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/titillium/TitilliumWeb-ExtraLightItalic.ttf
         weight: 200
         style: italic
       - asset: assets/fonts/titillium/TitilliumWeb-Light.ttf
         weight: 300
       - asset: assets/fonts/titillium/TitilliumWeb-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
         weight: 400
       - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
         weight: 400
         style: italic
       - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/titillium/TitilliumWeb-SemiBoldItalic.ttf
         weight: 600
         style: italic
       - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
         weight: 700
       - asset: assets/fonts/titillium/TitilliumWeb-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: assets/fonts/titillium/TitilliumWeb-Black.ttf
         weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

